class Locations {
  String? docId,
      locatId,
      name,
      anotherName,
      category,
      icon,
      address,
      lat,
      lng,
      website,
      workdate,
      timedate,
      tel,
      fax,
      email,
      image,
      createAt,
      editAt;

  Locations({
    required this.docId,
    required this.locatId,
    required this.name,
    required this.anotherName,
    required this.category,
    required this.icon,
    required this.address,
    required this.lat,
    required this.lng,
    required this.website,
    required this.workdate,
    required this.timedate,
    required this.tel,
    required this.fax,
    required this.email,
    required this.image,
    required this.createAt,
    required this.editAt,
  });
}
